<template>
  <section class="stage-panel">
    <header><p class="eyebrow">STEP 7</p><h2>审核修订</h2><p>高风险问题未解决时不能通过本集，点击提示可回到筛选后的问题列表。</p></header>
    <div class="toolbar"><el-select v-model="state.filters.severities" multiple clearable placeholder="严重度"><el-option v-for="item in ['BLOCKER','HIGH','MEDIUM','LOW']" :key="item" :value="item" /></el-select><el-button data-action="filter-review-issues" @click="applyFilter">筛选问题</el-button></div>
    <div ref="issueList" class="issues" :class="{focused:state.focusIssueList}"><article v-for="issue in visibleIssues" :key="issue.id" class="issue"><div><el-tag :type="['BLOCKER','HIGH'].includes(issue.severity)?'danger':'warning'">{{ issue.severity }}</el-tag><strong>{{ issue.title || issue.id }}</strong><p>{{ issue.message }}</p></div><el-button data-action="save-local-revision" @click="openRevision(issue)">保存局部修订</el-button></article><el-empty v-if="!visibleIssues.length" description="当前筛选无问题" /></div>
    <div class="toolbar"><el-button data-action="compare-revision" @click="compare">对比修订前后</el-button><el-button data-action="regenerate-current-artifact" @click="regenerate">重新生成当前产物</el-button><el-button type="primary" data-action="approve-episode" @click="approve">审核通过本集</el-button></div>
    <el-dialog v-model="revisionVisible" title="局部修订" width="600px"><el-input v-model="revisionAfter" type="textarea" :rows="8" /><template #footer><el-button @click="revisionVisible=false">取消</el-button><el-button type="primary" @click="saveRevision">保存修订</el-button></template></el-dialog>
    <el-dialog :model-value="!!state.comparison" title="修订前后对比" width="760px" @close="state.comparison=null"><div class="compare"><pre>{{ state.comparison?.before }}</pre><pre>{{ state.comparison?.after }}</pre></div></el-dialog>
  </section>
</template>
<script setup>
import { nextTick,reactive,ref,watch } from 'vue';import { approveReviewEpisode,compareReviewRevision,createReviewState,filterReviewIssues,saveLocalRevision } from '../workbench/downstreamStageModel.js';import { runArtifactRegeneration } from '../workbench/upstreamStageModel.js'
const props=defineProps({modelValue:{type:Object,default:()=>({})},episodeId:{type:String,default:''},saveRevisionAdapter:Function,approveAdapter:Function,regenerateArtifactAdapter:Function,workbench:Object,generationInput:{type:Object,default:()=>({})}});const emit=defineEmits(['update:modelValue','guidance','result']);const state=reactive(createReviewState(props.modelValue));const visibleIssues=ref(filterReviewIssues(state));const issueList=ref(null);const revisionVisible=ref(false);const revisionIssueId=ref(null);const revisionAfter=ref('');watch(()=>props.modelValue,v=>{Object.assign(state,createReviewState(v));visibleIssues.value=filterReviewIssues(state)},{deep:true});const sync=()=>emit('update:modelValue',JSON.parse(JSON.stringify(state)));function done(v){if(v?.allowed===false)emit('guidance',v);else{sync();emit('result',v)};return v}
function applyFilter(){visibleIssues.value=filterReviewIssues(state);sync()}function openRevision(issue){revisionIssueId.value=issue.id;revisionAfter.value=issue.content||'';revisionVisible.value=true}async function saveRevision(){const result=await saveLocalRevision(state,revisionIssueId.value,{after:revisionAfter.value},props.saveRevisionAdapter);if(result?.allowed!==false){revisionVisible.value=false;visibleIssues.value=filterReviewIssues(state)}return done(result)}function compare(){const last=state.revisions.at(-1);return done(compareReviewRevision(state,last?.id))}async function approve(){const result=await approveReviewEpisode(state,props.episodeId,props.approveAdapter);if(result?.allowed===false){visibleIssues.value=filterReviewIssues(state);await nextTick();issueList.value?.scrollIntoView?.({behavior:'smooth',block:'start'})}return done(result)}async function regenerate(){return done(await runArtifactRegeneration({workbench:props.workbench,input:{...props.generationInput,subtask:'重新生成审核修订产物'},execute:props.regenerateArtifactAdapter}))}
</script>
<style scoped>.stage-panel{display:grid;gap:14px}.eyebrow{color:var(--el-color-primary);font-weight:700}.toolbar{display:flex;justify-content:flex-end;gap:8px}.issues{display:grid;gap:10px}.issues.focused{box-shadow:0 0 0 2px var(--el-color-danger);border-radius:10px}.issue{display:flex;justify-content:space-between;gap:16px;border:1px solid var(--el-border-color);border-radius:10px;padding:14px}.issue>div{display:grid;grid-template-columns:auto 1fr;gap:8px;align-items:center}.issue p{grid-column:1/-1;margin:0;color:var(--el-text-color-secondary)}.compare{display:grid;grid-template-columns:1fr 1fr;gap:12px}.compare pre{white-space:pre-wrap;border:1px solid var(--el-border-color);padding:12px;border-radius:8px}</style>
