<template>
  <section class="stage-panel">
    <header><p class="eyebrow">STEP 8</p><h2>文字分镜</h2><p>镜头操作保留精确场景资产版本；归档和画布创建只接受已锁定快照。</p></header>
    <div class="toolbar"><el-select v-model="activeSceneId" placeholder="选择新增镜头所属场景"><el-option v-for="scene in storyboardScenes" :key="scene.id" :label="scene.title||scene.heading||scene.id" :value="scene.id" /></el-select><el-button data-action="add-shot" @click="addShot">新增镜头</el-button><el-button data-action="split-shot" @click="splitShot">拆分镜头</el-button><el-button data-action="merge-shot" @click="mergeShots">合并镜头</el-button><el-button data-action="toggle-shot-view" @click="toggleView">切换{{ state.viewMode==='card'?'表格':'卡片' }}</el-button></div>
    <div v-if="state.viewMode==='card'" class="shot-grid"><button v-for="shot in state.shots" :key="shot.id" class="shot" :class="{selected:selectedIds.includes(shot.id)}" @click="toggleSelect(shot.id)"><strong>{{ shot.id }}</strong><span>{{ shot.description || '空镜头' }}</span><small>{{ shot.assetBinding?`资产 v${shot.assetBinding.sceneAssetVersionId}`:'未绑定资产' }} · {{ shot.snapshotLocked?'快照已锁定':'快照未锁定' }}</small></button></div>
    <el-table v-else :data="state.shots" @selection-change="rows=>selectedIds=rows.map(row=>row.id)"><el-table-column type="selection" /><el-table-column prop="id" label="镜头 ID" /><el-table-column prop="description" label="画面" /></el-table>
    <section v-if="state.continuity.status!=='NOT_RUN'" class="continuity"><el-alert :type="state.continuity.passed?'success':'error'" :title="state.continuity.passed?'连续性检查通过':'连续性检查未通过'" :closable="false" /><div v-for="(issues,key) in state.continuity.groups" :key="key" v-show="issues.length"><strong>{{ continuityLabels[key] }}</strong><ul><li v-for="issue in issues" :key="issue.id||`${issue.code}-${issue.sceneId}`">{{ issue.sceneId }} · {{ issue.code }} · {{ issue.message }}</li></ul></div></section>
    <div class="toolbar"><el-button data-action="run-continuity-check" @click="continuity">连续性检查</el-button><el-button data-action="configure-mindmap" @click="mindmapVisible=true">配置导图</el-button><el-button data-action="create-canvas-project" @click="canvasVisible=true">创建画布项目</el-button><el-button data-action="regenerate-current-artifact" @click="regenerate">重新生成当前产物</el-button><el-button type="primary" data-action="complete-and-archive" @click="archive">完成并归档</el-button></div>
    <el-dialog v-model="mindmapVisible" title="配置导图"><el-form label-position="top"><el-form-item label="中心主题"><el-input v-model="mindmapDraft.title" /></el-form-item><el-form-item label="分组方式"><el-select v-model="mindmapDraft.groupBy"><el-option value="scene" label="按场景"/><el-option value="character" label="按角色"/></el-select></el-form-item></el-form><template #footer><el-button @click="mindmapVisible=false">取消</el-button><el-button type="primary" @click="saveMindmap">保存配置</el-button></template></el-dialog>
    <el-dialog v-model="canvasVisible" title="创建画布项目"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="canvasDraft.name" /></el-form-item><el-form-item label="用途"><el-input v-model="canvasDraft.purpose" /></el-form-item></el-form><template #footer><el-button @click="canvasVisible=false">取消</el-button><el-button type="primary" @click="createCanvas">创建</el-button></template></el-dialog>
  </section>
</template>
<script setup>
import { reactive,ref,watch } from 'vue';import { addStoryboardShot,archiveStoryboard,configureMindmap,createCanvasProject,createStoryboardState,mergeStoryboardShots,runContinuityCheck,splitStoryboardShot,toggleShotView } from '../workbench/downstreamStageModel.js';import { runArtifactRegeneration } from '../workbench/upstreamStageModel.js'
const props=defineProps({modelValue:{type:Object,default:()=>({})},storyboardScenes:{type:Array,default:()=>[]},addShotAdapter:Function,splitShotAdapter:Function,mergeShotAdapter:Function,continuityAdapter:Function,archiveAdapter:Function,mindmapAdapter:Function,canvasAdapter:Function,regenerateArtifactAdapter:Function,workbench:Object,generationInput:{type:Object,default:()=>({})}});const emit=defineEmits(['update:modelValue','guidance','result','archived','canvas-created']);const state=reactive(createStoryboardState(props.modelValue));let selectedIds=ref([]);const activeSceneId=ref(props.storyboardScenes[0]?.id??null);const mindmapVisible=ref(false),canvasVisible=ref(false);const mindmapDraft=reactive({title:'故事分镜导图',groupBy:'scene'}),canvasDraft=reactive({name:'',purpose:'production'});const continuityLabels={scene:'场景',variant:'变体',fixedProp:'固定道具',characterState:'角色状态',axis:'轴线'};watch(()=>props.modelValue,v=>Object.assign(state,createStoryboardState(v)),{deep:true});watch(()=>props.storyboardScenes,scenes=>{if(!scenes.some(scene=>scene.id===activeSceneId.value))activeSceneId.value=scenes[0]?.id??null},{deep:true});const sync=()=>emit('update:modelValue',JSON.parse(JSON.stringify(state)));function done(v,event){if(v?.allowed===false)emit('guidance',v);else{sync();emit('result',v);if(event)emit(event,v)}return v}function toggleSelect(id){selectedIds.value=selectedIds.value.includes(id)?selectedIds.value.filter(item=>item!==id):[...selectedIds.value,id]}function toggleView(){toggleShotView(state);sync()}
async function addShot(){return done(await addStoryboardShot(state,{sceneId:activeSceneId.value,description:'新镜头'},props.addShotAdapter))}async function splitShot(){return done(await splitStoryboardShot(state,selectedIds.value[0],props.splitShotAdapter))}async function mergeShots(){return done(await mergeStoryboardShots(state,selectedIds.value,props.mergeShotAdapter))}async function continuity(){return done(await runContinuityCheck(state,props.continuityAdapter))}async function archive(){return done(await archiveStoryboard(state,props.archiveAdapter),'archived')}async function saveMindmap(){const result=await configureMindmap(state,mindmapDraft,props.mindmapAdapter);if(result?.allowed!==false)mindmapVisible.value=false;return done(result)}async function createCanvas(){const result=await createCanvasProject(state,canvasDraft,props.canvasAdapter);if(result?.allowed!==false)canvasVisible.value=false;return done(result,'canvas-created')}async function regenerate(){return done(await runArtifactRegeneration({workbench:props.workbench,input:{...props.generationInput,subtask:'重新生成文字分镜'},execute:props.regenerateArtifactAdapter}))}
</script>
<style scoped>.stage-panel{display:grid;gap:14px}.eyebrow{color:var(--el-color-primary);font-weight:700}.toolbar{display:flex;justify-content:flex-end;flex-wrap:wrap;gap:8px}.shot-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px}.shot{display:grid;gap:8px;text-align:left;border:1px solid var(--el-border-color);background:var(--el-fill-color-blank);padding:14px;border-radius:10px;cursor:pointer}.shot.selected{border-color:var(--el-color-primary)}.shot small,header p{color:var(--el-text-color-secondary)}.continuity{display:grid;gap:10px;border:1px solid var(--el-border-color);padding:14px;border-radius:10px}.continuity ul{margin:6px 0}</style>
