-- V11: Agent Configuration Center — 6 tables + 4 Blueprint seeds
-- M1 scope: Blueprints, User Definitions, Versions, Bindings, Test Runs, Execution Snapshots

CREATE TABLE IF NOT EXISTS agent_blueprints (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL UNIQUE COMMENT '稳定外部ID，如 bp-hook-v1',
    role_type ENUM('HOOK','SCREENWRITER','STORYBOARD','DIRECTOR') NOT NULL COMMENT '角色类型',
    name VARCHAR(200) NOT NULL COMMENT 'Blueprint 名称',
    description VARCHAR(1000) COMMENT '能力说明',
    parameter_schema_json JSON NOT NULL COMMENT '结构化参数 JSON Schema',
    default_parameters_json JSON NOT NULL COMMENT '默认参数值',
    locked_system_prompt TEXT NOT NULL COMMENT '平台锁定 System Prompt',
    editable_prompt_template TEXT NOT NULL COMMENT '用户可编辑 Prompt 模板',
    input_schema_json JSON NOT NULL COMMENT '输入 Schema',
    output_schema_json JSON NOT NULL COMMENT '输出 Schema',
    allowed_tools_json JSON NOT NULL COMMENT '工具白名单',
    context_policy_json JSON NOT NULL COMMENT '上下文策略',
    model_policy_json JSON NOT NULL COMMENT '模型策略',
    blueprint_version INT NOT NULL DEFAULT 1 COMMENT 'Blueprint 版本号',
    status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_blueprint_role_version (role_type, blueprint_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent 系统基础框架';

CREATE TABLE IF NOT EXISTS user_agent_definitions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL UNIQUE COMMENT '稳定外部ID',
    blueprint_id BIGINT NOT NULL COMMENT '所属 Blueprint',
    owner_user_id BIGINT NOT NULL COMMENT '所有者',
    current_published_version_id BIGINT COMMENT '当前发布版本',
    name VARCHAR(120) NOT NULL COMMENT 'Agent 名称',
    description VARCHAR(1000) COMMENT '用途描述',
    icon VARCHAR(500) COMMENT '图标 URL',
    applicable_genres_json JSON COMMENT '适用题材',
    platforms_json JSON COMMENT '适用平台',
    visibility ENUM('PRIVATE','TEAM') NOT NULL DEFAULT 'PRIVATE' COMMENT '可见性',
    lifecycle_status ENUM('ACTIVE','ARCHIVED') NOT NULL DEFAULT 'ACTIVE' COMMENT '生命周期状态',
    row_version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_owner_name (owner_user_id, name),
    INDEX idx_blueprint (blueprint_id),
    INDEX idx_owner (owner_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户 Agent 定义';

CREATE TABLE IF NOT EXISTS agent_versions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL UNIQUE COMMENT '稳定外部ID',
    user_agent_id BIGINT NOT NULL COMMENT '所属 UserAgent',
    blueprint_id BIGINT NOT NULL COMMENT '所属 Blueprint（冗余，快照完整性）',
    version_no INT NOT NULL COMMENT '版本序号，从 1 递增',
    parameters_json JSON COMMENT '结构化业务参数',
    editable_prompt TEXT COMMENT '用户可编辑 Prompt',
    examples_json JSON COMMENT 'Few-shot 示例',
    model_policy_json JSON COMMENT '模型策略',
    status ENUM('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT' COMMENT '版本状态',
    change_summary VARCHAR(500) COMMENT '版本说明',
    content_hash VARCHAR(64) COMMENT '内容哈希',
    created_by BIGINT COMMENT '创建者',
    published_by BIGINT COMMENT '发布者',
    published_at DATETIME COMMENT '发布时间',
    row_version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_agent_version (user_agent_id, version_no),
    INDEX idx_user_agent (user_agent_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent 版本';

CREATE TABLE IF NOT EXISTS agent_bindings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL UNIQUE COMMENT '稳定外部ID',
    scope_type ENUM('USER','PROJECT') NOT NULL COMMENT '作用域类型',
    scope_id VARCHAR(50) NOT NULL COMMENT '作用域 ID（用户ID或项目ID）',
    role_type ENUM('HOOK','SCREENWRITER','STORYBOARD','DIRECTOR') NOT NULL COMMENT '角色类型',
    user_agent_id BIGINT NOT NULL COMMENT '绑定的 UserAgent',
    agent_version_id BIGINT NOT NULL COMMENT '绑定的发布版本',
    created_by BIGINT COMMENT '创建者',
    updated_by BIGINT COMMENT '更新者',
    row_version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_scope_role (scope_type, scope_id, role_type),
    INDEX idx_agent_version (agent_version_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent 绑定';

CREATE TABLE IF NOT EXISTS agent_test_runs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL UNIQUE COMMENT '稳定外部ID',
    agent_version_id BIGINT NOT NULL COMMENT '测试的版本',
    input_snapshot_json JSON COMMENT '测试输入快照',
    context_snapshot_json JSON COMMENT '上下文快照',
    output_json JSON COMMENT '模型输出',
    output_schema_valid TINYINT COMMENT '输出是否通过 Schema 校验',
    model_id VARCHAR(100) COMMENT '使用的模型',
    prompt_tokens INT COMMENT 'Prompt tokens',
    completion_tokens INT COMMENT 'Completion tokens',
    credit_cost DECIMAL(10,4) COMMENT '费用',
    duration_ms INT COMMENT '耗时（毫秒）',
    status ENUM('PENDING','RUNNING','SUCCEEDED','FAILED') NOT NULL DEFAULT 'PENDING' COMMENT '试跑状态',
    error_code VARCHAR(50) COMMENT '错误码',
    error_message VARCHAR(2000) COMMENT '错误信息',
    created_by BIGINT COMMENT '操作者',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_version (agent_version_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent 试跑记录';

CREATE TABLE IF NOT EXISTS agent_execution_snapshots (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL UNIQUE COMMENT '稳定外部ID',
    blueprint_id BIGINT NOT NULL COMMENT 'Blueprint ID',
    blueprint_version INT NOT NULL COMMENT 'Blueprint 版本号',
    user_agent_id BIGINT COMMENT 'UserAgent ID',
    agent_version_id BIGINT COMMENT 'AgentVersion ID',
    binding_source ENUM('USER','PROJECT','SYSTEM','TEMPORARY') NOT NULL COMMENT '配置来源',
    resolved_parameters_json JSON COMMENT '解析后的参数',
    temporary_overrides_json JSON COMMENT '临时覆盖参数',
    resolved_prompt TEXT COMMENT '最终编译 Prompt',
    prompt_hash VARCHAR(64) COMMENT 'Prompt 哈希',
    output_schema_version VARCHAR(50) COMMENT '输出 Schema 版本',
    project_id BIGINT COMMENT '关联项目',
    context_hash VARCHAR(64) COMMENT '上下文哈希',
    context_refs_json JSON COMMENT '上下文引用',
    business_task_type VARCHAR(50) COMMENT '业务任务类型',
    business_task_id VARCHAR(100) COMMENT '业务任务 ID',
    model_id VARCHAR(100) COMMENT '使用的模型',
    created_by BIGINT COMMENT '创建者',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_agent_version (agent_version_id),
    INDEX idx_project (project_id),
    INDEX idx_business_task (business_task_type, business_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent 执行快照';

-- 4 Blueprint 种子数据
INSERT IGNORE INTO agent_blueprints (uuid, role_type, name, description, parameter_schema_json, default_parameters_json, locked_system_prompt, editable_prompt_template, input_schema_json, output_schema_json, allowed_tools_json, context_policy_json, model_policy_json, blueprint_version, status)
VALUES
('bp-hook-v1', 'HOOK', '钩子 Agent', '钩子生成、分析和审核',
 '{"type":"object","additionalProperties":false,"properties":{"opening_seconds":{"type":"integer","minimum":1,"maximum":10,"default":3,"description":"开场抓人秒数"},"hook_density":{"type":"string","enum":["low","medium","high","extreme"],"enumLabels":["低","中","高","极高"],"default":"medium","description":"钩子密度"},"reversal_strength":{"type":"number","minimum":0,"maximum":1,"default":0.5,"description":"反转强度"},"closing_hook_strength":{"type":"string","enum":["weak","moderate","strong"],"enumLabels":["弱","中","强"],"default":"moderate","description":"章尾悬念强度"},"minimum_score":{"type":"integer","minimum":0,"maximum":100,"default":60,"description":"钩子最低通过分"}}}',
 '{"opening_seconds":3,"hook_density":"medium","reversal_strength":0.5,"closing_hook_strength":"moderate","minimum_score":60}',
 '平台锁定：仅生成钩子结构。你必须严格遵循以下工具权限、安全规则和输出协议。不得输出与钩子无关的内容。',
 '{{user_method}}',
 '{"type":"object","properties":{"script_excerpt":{"type":"string","description":"待分析的剧本片段"}}}',
 '{"type":"object","properties":{"score":{"type":"integer"},"hooks":{"type":"array"},"analysis":{"type":"string"}}}',
 '[]',
 '{"max_context_length":16000,"allowed_context_types":["script","bible","project_constraints"]}',
 '{"default_model":"deepseek-v3","fallback_model":"gpt-4o","max_tokens":4096,"temperature":{"min":0.3,"max":1.2,"default":0.7}}',
 1, 'ACTIVE'),

('bp-screenwriter-v1', 'SCREENWRITER', '编剧 Agent', '大纲、分集、正文生成和编剧修订',
 '{"type":"object","additionalProperties":false,"properties":{"revision_mode":{"type":"string","enum":["conservative","balanced","rewrite"],"default":"balanced","description":"修订强度"},"target_duration_seconds":{"type":"integer","minimum":30,"maximum":600,"default":180,"description":"单集目标时长（秒）"},"dialogue_density":{"type":"string","enum":["sparse","normal","dense"],"default":"normal","description":"对白密度"},"conflict_pace":{"type":"string","enum":["slow","moderate","fast","intense"],"default":"moderate","description":"冲突升级速度"},"character_consistency":{"type":"string","enum":["loose","normal","strict"],"default":"normal","description":"人物一致性要求"}}}',
 '{"revision_mode":"balanced","target_duration_seconds":180,"dialogue_density":"normal","conflict_pace":"moderate","character_consistency":"normal"}',
 '平台锁定：仅执行编剧任务。你必须严格遵循创作圣经和项目约束。所有输出必须符合剧本格式规范。',
 '{{user_method}}',
 '{"type":"object","properties":{"task_type":{"type":"string","enum":["outline","episode","body","revise"]},"context":{"type":"string"}}}',
 '{"type":"object","properties":{"content":{"type":"string"},"revision_summary":{"type":"string"}}}',
 '[]',
 '{"max_context_length":32000,"allowed_context_types":["script","bible","project_constraints","character_profiles"]}',
 '{"default_model":"deepseek-v3","fallback_model":"gpt-4o","max_tokens":8192,"temperature":{"min":0.3,"max":1.2,"default":0.7}}',
 1, 'ACTIVE'),

('bp-storyboard-v1', 'STORYBOARD', '分镜 Agent', 'A/B/C 档分镜生成和镜头策略',
 '{"type":"object","additionalProperties":false,"properties":{"tier":{"type":"string","enum":["A","B","C"],"default":"B","description":"分镜档位"},"average_shot_seconds":{"type":"number","minimum":1,"maximum":30,"default":4,"description":"平均镜头时长（秒）"},"shot_density":{"type":"string","enum":["sparse","normal","dense"],"default":"normal","description":"镜头密度"},"camera_complexity":{"type":"string","enum":["simple","moderate","complex"],"default":"moderate","description":"运镜复杂度"},"continuity_level":{"type":"string","enum":["basic","standard","strict"],"default":"standard","description":"连续性要求"},"production_cost_mode":{"type":"string","enum":["low","balanced","quality_first"],"default":"balanced","description":"制片成本策略"}}}',
 '{"tier":"B","average_shot_seconds":4,"shot_density":"normal","camera_complexity":"moderate","continuity_level":"standard","production_cost_mode":"balanced"}',
 '平台锁定：输出专业分镜结构。你必须输出符合行业标准的分镜脚本格式，包含镜头号、景别、运镜、动作、对白、时长。',
 '{{user_method}}',
 '{"type":"object","properties":{"script_text":{"type":"string"},"bible_context":{"type":"string"},"tier_override":{"type":"string","enum":["A","B","C"]}}}',
 '{"type":"object","properties":{"shots":{"type":"array"},"summary":{"type":"string"},"estimated_duration_seconds":{"type":"number"}}}',
 '[]',
 '{"max_context_length":16000,"allowed_context_types":["script","bible","character_profiles","scene_descriptions"]}',
 '{"default_model":"deepseek-v3","fallback_model":"gpt-4o","max_tokens":8192,"temperature":{"min":0.2,"max":1.0,"default":0.6}}',
 1, 'ACTIVE'),

('bp-director-v1', 'DIRECTOR', '导演 Agent', '节奏、画面、可拍性和导演审核',
 '{"type":"object","additionalProperties":false,"properties":{"visual_style":{"type":"string","enum":["realistic","stylized","cinematic","minimalist"],"default":"cinematic","description":"视觉风格"},"pacing_mode":{"type":"string","enum":["slow_burn","balanced","fast_paced","rhythmic"],"default":"balanced","description":"节奏模式"},"feasibility_level":{"type":"string","enum":["strict","pragmatic","creative"],"default":"pragmatic","description":"可拍性要求"},"budget_mode":{"type":"string","enum":["micro","low","medium","unlimited"],"default":"medium","description":"预算约束"},"approval_threshold":{"type":"integer","minimum":50,"maximum":100,"default":70,"description":"审核通过阈值"},"output_mode":{"type":"string","enum":["review_only","suggestions","patch","full_revision"],"default":"suggestions","description":"输出模式"}}}',
 '{"visual_style":"cinematic","pacing_mode":"balanced","feasibility_level":"pragmatic","budget_mode":"medium","approval_threshold":70,"output_mode":"suggestions"}',
 '平台锁定：输出导演审核结构。你必须输出评分、问题列表、严重度分级、建议和可执行修订项。不得跳过可拍性检查。',
 '{{user_method}}',
 '{"type":"object","properties":{"script_or_storyboard":{"type":"string"},"bible_context":{"type":"string"},"budget_constraints":{"type":"object"}}}',
 '{"type":"object","properties":{"overall_score":{"type":"integer"},"issues":{"type":"array"},"suggestions":{"type":"array"},"feasibility_report":{"type":"string"}}}',
 '[]',
 '{"max_context_length":32000,"allowed_context_types":["script","storyboard","bible","budget","production_constraints"]}',
 '{"default_model":"deepseek-v3","fallback_model":"gpt-4o","max_tokens":8192,"temperature":{"min":0.1,"max":0.8,"default":0.4}}',
 1, 'ACTIVE');
