<template>
  <el-drawer :model-value="modelValue" size="760px" :with-header="false" @close="close">
    <div v-if="asset" class="drawer-content">
      <header class="drawer-heading"><div><small>{{ asset.stableId || asset.uuid || `SCENE-${asset.id}` }}</small><h2>{{ asset.name }}</h2><p>v{{ asset.currentVersionNo || 1 }} · {{ asset.status || 'ACTIVE' }} · {{ selectedSyncStatus }}</p></div><div><el-button data-action="view-impact" @click="refreshImpact">查看影响</el-button><el-button @click="close">关闭</el-button></div></header>
      <el-tabs v-model="activeTab" @tab-change="beginDraft">
        <el-tab-pane label="基础信息" name="basic">
          <el-form label-position="top"><el-form-item label="场景名称" :error="errors.name"><el-input v-model="draft.name" /></el-form-item><div class="form-grid"><el-form-item label="空间类型" :error="errors.spaceType"><el-select v-model="draft.spaceType"><el-option label="室内" value="INTERIOR" /><el-option label="室外" value="EXTERIOR" /><el-option label="混合" value="MIXED" /></el-select></el-form-item><el-form-item label="复用级别" :error="errors.reusability"><el-select v-model="draft.reusability"><el-option label="高" value="HIGH" /><el-option label="中" value="MEDIUM" /><el-option label="低" value="LOW" /></el-select></el-form-item><el-form-item label="现实类型" :error="errors.realityType"><el-input v-model="draft.realityType" /></el-form-item></div><el-form-item label="来源地点"><el-input v-model="draft.worldLocationRef" /></el-form-item></el-form>
        </el-tab-pane>
        <el-tab-pane label="视觉设定" name="visual">
          <el-form label-position="top"><el-form-item label="空间布局"><el-input v-model="draft.layout" type="textarea" /></el-form-item><el-form-item label="材质 / 色板 / 灯光"><el-input v-model="draft.visualText" type="textarea" :rows="4" /></el-form-item><el-form-item label="地标（每行一个）"><el-input v-model="draft.landmarksText" type="textarea" /></el-form-item><el-form-item label="生成提示词"><el-input v-model="draft.prompts" type="textarea" /></el-form-item></el-form>
        </el-tab-pane>
        <el-tab-pane label="场景变体" name="variants">
          <div v-for="variant in asset.variants || []" :key="variant.id" class="variant-row"><div><strong>{{ variant.name || variant.id }}</strong><p>{{ variant.id }} · v{{ variant.version }}</p></div><el-button @click="editVariant(variant)">编辑</el-button></div>
          <el-button @click="newVariant">+ 新增变体</el-button>
          <el-form v-if="variantDraft.open" label-position="top" class="variant-editor"><el-form-item label="变体名称" :error="errors.variantName"><el-input v-model="variantDraft.name" /></el-form-item><el-form-item label="时间 / 事件状态"><el-input v-model="variantDraft.time" /><el-input v-model="variantDraft.eventState" /></el-form-item><el-form-item label="灯光差量"><el-input v-model="variantDraft.lightingDelta" /></el-form-item><div class="editor-actions"><el-button @click="cancelVariant">取消</el-button><el-button type="primary" @click="saveVariant">保存变体</el-button></div></el-form>
        </el-tab-pane>
        <el-tab-pane label="连续性" name="continuity">
          <el-form label-position="top"><el-form-item label="固定道具（每行一个）"><el-input v-model="draft.fixedPropsText" type="textarea" :rows="4" /></el-form-item><el-form-item label="出入口"><el-input v-model="draft.entrancesExitsText" type="textarea" /></el-form-item><el-form-item label="连续性规则（每行一条）"><el-input v-model="draft.continuityRulesText" type="textarea" :rows="6" /></el-form-item></el-form>
        </el-tab-pane>
        <el-tab-pane label="引用 / 版本" name="references-versions">
          <section class="reference-summary"><p>引用 {{ impactData?.references?.length || asset.episodeReferenceCount || 0 }} 处；待同步 {{ impactData?.staleReferences || 0 }} 处；锁定 {{ impactData?.lockedReferences || 0 }} 处。</p><el-button data-action="replace-reference" @click="openReplace">创建替代并迁移引用</el-button><el-button type="warning" @click="deactivate">停用</el-button></section>
          <div v-for="reference in projectedConsumers" :key="`${reference.type}-${reference.id}`" class="consumer-row"><div><strong>{{ reference.type }} #{{ reference.id }}</strong><p>v{{ reference.versionId || '—' }} · {{ reference.downstreamStatus }}</p></div><div><el-button @click="resolve(reference, 'view-diff')">查看差异</el-button><el-button v-if="reference.downstreamStatus === 'STALE'" @click="resolve(reference, 'keep-old')">保留旧版</el-button><el-button v-if="reference.downstreamStatus === 'STALE'" type="primary" @click="resolve(reference, 'upgrade-new')">升级新版</el-button></div></div>
          <h3>版本记录</h3><div v-for="version in versions" :key="version.id" class="version-row"><span>v{{ version.versionNo }} · {{ version.changeNote || '无变更说明' }}</span><el-button data-action="restore-version" @click="prepareRestore(version)">恢复此版本</el-button></div><div v-if="!versions.length" class="version-row"><el-input v-model="manualVersionId" placeholder="输入历史版本主键 ID" /><el-button data-action="restore-version" @click="prepareManualRestore">查看影响并恢复</el-button></div>
        </el-tab-pane>
      </el-tabs>
      <div v-if="activeTab !== 'variants' && activeTab !== 'references-versions'" class="editor-actions"><el-button @click="cancelDraft">取消修改</el-button><el-button type="primary" @click="saveDraft">保存并生成新版本</el-button></div>
      <el-alert v-if="currentResult?.impactRefresh?.ok === false" type="warning" :title="currentResult.impactRefresh.message" :closable="false" show-icon><el-button text @click="refreshImpact">重试影响范围</el-button></el-alert>
      <section v-if="currentResult" class="action-result"><div><strong>可追溯操作结果</strong><p>{{ currentResult.action }} · {{ currentResult.createdAt }} · 影响 {{ currentResult.affectedConsumers?.length || 0 }} 处</p></div><el-button @click="emit('open-result', currentResult)">重新查看</el-button></section>
    </div>

    <el-dialog v-model="impactConfirmationVisible" class="impact-confirmation" title="确认版本影响" width="620px" append-to-body :close-on-click-modal="false"><p>本操作可能影响 {{ pendingImpact?.references?.length || 0 }} 个剧本场景/分镜，未锁定项将进入 STALE，已锁定快照保持原版本。</p><template v-if="pendingAction?.type === 'replace'"><el-radio-group v-model="replacementMode"><el-radio value="existing">迁移到已有资产</el-radio><el-radio value="create">创建替代资产</el-radio></el-radio-group><el-input v-if="replacementMode === 'existing'" v-model="replacementAssetId" placeholder="替代场景资产 ID" /><el-form v-else label-position="top"><el-form-item label="替代资产名称"><el-input v-model="replacementDraft.name" /></el-form-item><div class="form-grid"><el-form-item label="空间类型"><el-input v-model="replacementDraft.spaceType" /></el-form-item><el-form-item label="复用级别"><el-input v-model="replacementDraft.reusability" /></el-form-item><el-form-item label="现实类型"><el-input v-model="replacementDraft.realityType" /></el-form-item></div></el-form></template><template #footer><el-button @click="impactConfirmationVisible=false">取消</el-button><el-button type="primary" @click="confirmImpactAction">确认并持久化</el-button></template></el-dialog>
  </el-drawer>
</template>

<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { classifySceneAssetChange, validateSceneAssetDraft } from '../workbench/sceneAssetModel.js'
import { impactConsumers } from '../workbench/sceneAssetUiModel.js'

const props = defineProps({ modelValue: Boolean, sceneAssets: { type: Object, required: true } })
const emit = defineEmits(['update:modelValue', 'guidance', 'open-result'])
const activeTab = ref('basic'); const draft = reactive({}); const errors = reactive({}); const variantDraft = reactive({ open: false, id: null, name: '', time: '', eventState: '', lightingDelta: '' })
const impactConfirmationVisible = ref(false); const pendingAction = ref(null); const pendingImpact = ref(null); const replacementAssetId = ref(''); const manualVersionId = ref(''); const replacementMode = ref('existing'); const replacementDraft = reactive({ name: '', spaceType: '', reusability: 'MEDIUM', realityType: 'REALISTIC' })
const sceneAssets = props.sceneAssets
const asset = computed(() => sceneAssets.selectedAsset.value)
const impactData = computed(() => sceneAssets.impact.value)
const versions = computed(() => asset.value?.versions || [])
const selectedSyncStatus = computed(() => asset.value?.syncStatus || (impactData.value?.staleReferences ? 'STALE' : 'CURRENT'))
const currentResult = computed(() => sceneAssets.actionResult.value?.data || null)
const projectedConsumers = computed(() => impactConsumers({ downstreamStatus: impactData.value?.staleReferences ? 'STALE' : 'CURRENT', affectedScopes: ['visual', 'continuity'] }, impactData.value || {}))
watch(asset, beginDraft, { immediate: true })
function clone(value) { return JSON.parse(JSON.stringify(value ?? {})) }
function lines(value) { return Array.isArray(value) ? value.join('\n') : (value || '') }
function fromLines(value) { return String(value || '').split('\n').map(item => item.trim()).filter(Boolean) }
function beginDraft() { const value = asset.value; if (!value) return; const master = value.master || {}; Object.keys(draft).forEach(key => delete draft[key]); Object.assign(draft, clone({ name: value.name, spaceType: master.spaceType, reusability: master.reusability, realityType: master.realityType, worldLocationRef: master.worldLocationRef, layout: master.layout, visualText: [master.materials, master.palette, master.lighting].flat().filter(Boolean).join('\n'), landmarksText: lines(master.landmarks), prompts: master.prompts, fixedPropsText: lines(master.fixedProps), entrancesExitsText: lines(master.entrancesExits), continuityRulesText: lines(master.continuityRules) })); Object.keys(errors).forEach(key => delete errors[key]) }
function close() { emit('update:modelValue', false) }
function guide(value) { emit('guidance', value); return value }
function cancelDraft() { beginDraft() }
function draftPayload() { if (activeTab.value === 'basic') return { name: draft.name, spaceType: draft.spaceType, reusability: draft.reusability, realityType: draft.realityType, worldLocationRef: draft.worldLocationRef }; if (activeTab.value === 'visual') return { layout: draft.layout, materials: fromLines(draft.visualText), landmarks: fromLines(draft.landmarksText), prompts: draft.prompts }; return { fixedProps: fromLines(draft.fixedPropsText), entrancesExits: fromLines(draft.entrancesExitsText), continuityRules: fromLines(draft.continuityRulesText) } }
async function saveDraft() { Object.keys(errors).forEach(key => delete errors[key]); const fullDraft = { ...asset.value?.master, name: draft.name, spaceType: draft.spaceType, reusability: draft.reusability, realityType: draft.realityType }; Object.assign(errors, validateSceneAssetDraft(fullDraft)); if (Object.keys(errors).length) return guide({ ok: false, code: 'VALIDATION_FAILED', message: '请修正标记字段', fieldErrors: clone(errors) }); const before = clone(asset.value); const expectedChange = classifySceneAssetChange(before, { ...before, master: { ...before.master, ...draftPayload() }, name: draft.name }); const result = await sceneAssets.update(asset.value.id, draftPayload()); if (!result.ok) return guide(result); if (expectedChange.downstreamStatus === 'STALE') await refreshImpact(); beginDraft(); return result }
function newVariant() { Object.assign(variantDraft, { open: true, id: null, name: '', time: '', eventState: '', lightingDelta: '' }); delete errors.variantName }
function editVariant(value) { Object.assign(variantDraft, { open: true, ...clone(value) }); delete errors.variantName }
function cancelVariant() { variantDraft.open = false }
async function saveVariant() { if (!variantDraft.name.trim()) { errors.variantName = '变体名称不能为空'; return guide({ ok: false, code: 'VARIANT_NAME_REQUIRED', message: errors.variantName }) } const payload = { name: variantDraft.name, time: variantDraft.time, eventState: variantDraft.eventState, lightingDelta: variantDraft.lightingDelta }; const result = variantDraft.id ? await sceneAssets.updateVariant(asset.value.id, variantDraft.id, payload) : await sceneAssets.createVariant(asset.value.id, payload); if (!result.ok) return guide(result); variantDraft.open = false; await refreshImpact(); return result }
async function refreshImpact() { const result = await sceneAssets.loadImpact(asset.value?.id); if (!result.ok) guide(result); return result }
async function prepareRestore(version) { const loaded = await refreshImpact(); if (!loaded.ok) return loaded; pendingAction.value = { type: 'restore', version }; pendingImpact.value = loaded.impact; impactConfirmationVisible.value = true }
function prepareManualRestore() { const id = Number(manualVersionId.value); if (!Number.isInteger(id) || id <= 0) return guide({ ok: false, code: 'RESTORE_VERSION_REQUIRED', message: '请输入有效的历史版本主键 ID' }); return prepareRestore({ id, versionNo: '历史' }) }
async function openReplace() { const loaded = await refreshImpact(); if (!loaded.ok) return loaded; pendingAction.value = { type: 'replace', sourceAssetId: asset.value.id }; pendingImpact.value = loaded.impact; replacementAssetId.value = ''; replacementMode.value = 'existing'; Object.assign(replacementDraft, { name: `${asset.value.name}-替代`, spaceType: asset.value.master?.spaceType || '', reusability: asset.value.master?.reusability || 'MEDIUM', realityType: asset.value.master?.realityType || 'REALISTIC' }); impactConfirmationVisible.value = true }
async function confirmImpactAction() { let result; if (pendingAction.value?.type === 'restore') result = await sceneAssets.restore(asset.value.id, pendingAction.value.version.id, { changeNote: '从资产管理界面恢复' }); else { let targetId = replacementAssetId.value.trim(); if (replacementMode.value === 'create') { const created = await sceneAssets.create({ ...replacementDraft }); if (!created.ok) return guide(created); targetId = String(created.data?.id || '') } if (!targetId) return guide({ ok: false, code: 'REPLACEMENT_ASSET_REQUIRED', message: '请选择替代资产或填写完整的新资产信息' }); result = await sceneAssets.replaceReferences(pendingAction.value.sourceAssetId, { assetId: targetId }) } if (!result.ok) return guide(result); impactConfirmationVisible.value = false; beginDraft(); return result }
async function deactivate() { const result = await sceneAssets.archive(asset.value.id); if (!result.ok) return guide(result); return result }
async function resolve(reference, decision) { const result = await sceneAssets.resolveConsumer(reference, decision); if (!result.ok) return guide(result); await refreshImpact(); return result }
</script>

<style scoped>
.drawer-content{display:grid;gap:16px;padding:22px}.drawer-heading,.drawer-heading>div,.editor-actions,.reference-summary,.consumer-row,.version-row,.variant-row,.action-result{display:flex;align-items:center;justify-content:space-between;gap:12px}.drawer-heading h2{margin:4px 0}.drawer-heading p,.variant-row p,.consumer-row p,.action-result p{color:var(--el-text-color-secondary)}.form-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.variant-row,.consumer-row,.version-row,.action-result{border:1px solid var(--el-border-color);border-radius:10px;padding:12px;margin-bottom:10px}.variant-editor{margin-top:14px;padding:14px;background:var(--el-fill-color-light);border-radius:10px}.reference-summary{flex-wrap:wrap;margin-bottom:14px}.editor-actions{justify-content:flex-end;margin-top:16px}@media(max-width:700px){.form-grid{grid-template-columns:1fr}.drawer-heading{align-items:flex-start;flex-direction:column}}
</style>
